image: docker:latest

cache:
  paths:
    - node_modules/

services:
  - name: docker:dind
    command: ["--insecure-registry=new001.suntrayoa.com"]


stages:
  - build
  - package
  - deploy

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

node-build:
  image: node:latest
  stage: build
  before_script:
    - 'npm install -g cnpm --registry=https://registry.npm.taobao.org'
  script: "cnpm install && cnpm run build"
  only:
    - demo
  artifacts:
    name: "dist"
    untracked: true
    paths:
      - $CI_PROJECT_DIR/dist

docker-build:
  stage: package
  script:
     - docker build --pull -t "$CI_REGISTRY_IMAGE" .
     - docker push "$CI_REGISTRY_IMAGE"
  dependencies:
    - node-build
  only:
    - demo


docker-run:
  stage: deploy
  
  before_script:
  
  - 'which ssh-agent || ( apk add --update git openssh-client bash )'
  
  - eval $(ssh-agent -s)
  
  - bash -c 'ssh-add <(echo "$SSH_PRIVATE_KEY")'
  
  - mkdir -p ~/.ssh
  
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

  only:
    - demo
  script:
    - ssh $CI_REGISTRY "sh /opt/docker-compose-file/deploy-devfront.sh"
  dependencies:
    - docker-build


